### ISSUE TITLE
Any chance for a TBC db dump now that Gummys Burning Crusade is just around the corner?

### ISSUE THREAD

**Issue by Larsy93** [Muehe/classicdb#3]
Any chance for a TBC db dump now that Gummys Burning Crusade is just around the corner?

**Comment by Muehe** [comment]
There are a few odds and ends to be taken care of before the final release for classic, next thing on the list is support for more languages and then TBC comes after that. Can't possibly give you an ETA currently as I'm rather busy. But I have to do some work on my database extractor anyway, I'll use the occasion to see if I can get it to work out of the box by just extracting a TBC DB.

**Comment by Larsy93** [comment]
Feel free to dump the db's in here if u dont mind :)

**Comment by Muehe** [comment]
This project is not in development anymore. If you still need a TBC addon, [pfQuest](https://gitlab.com/shagu/pfQuest) is developing one.
