### ISSUE TITLE
Feature request: Show more details about items and quests

### ISSUE THREAD

**Issue by FrostShock** [Muehe/classicdb#6]
This is a great addon, however I would like to place the following feature requests:
- when you find a quest and click on it, show quest rewards
- when you find an item and click on it, show the name of the mobs dropping it and of the NPCs selling it - and where those mobs and NPCs are located.

**Comment by Muehe** [comment]
Sorry for the late reply.

This project is not active anymore, as mentioned in the Readme. Try [pfQuest](https://github.com/shagu/pfQuest).
